import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Button from '@material-ui/core/Button';
import Typography from '@material-ui/core/Typography';
import EmojiFoodBeverageIcon from '@material-ui/icons/EmojiFoodBeverage';
import LogoDevIcon from '@mui/icons-material/LogoDev';
import { Icon } from '@iconify/react';


export default function Home() {
  const wishListUrl = "https://www.amazon.jp/hz/wishlist/ls/249DH0KL7DT0K?ref_=wl_share"
  const devToUrl = "https://dev.to/kaede_io"
  return (
    <div className={styles.container}>
      <Head>
        <title>kaede site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Typography variant="caption" display="block" gutterBottom>
          エンジニア
        </Typography>
        <Typography variant="h4" gutterBottom component="div">
          カエデ (kaede0902)
        </Typography>
        <Typography variant="h5" gutterBottom component="div">
          公式サイト
        </Typography>

        <p className={styles.description}>
          
        </p>

        <Typography variant="caption" display="block" gutterBottom>
          Web Developer
        </Typography>
        <Typography variant="h4" gutterBottom component="div">
          kaede (kaede0902)
        </Typography>
        <Typography variant="h5" gutterBottom component="div">
          Offical Web Site
        </Typography>
        <p className={styles.description}>
          WELCOME.
        </p>

        <Button
          href={wishListUrl}
          target="_blank"
          variant="contained"
          size='large'
          style={{
            background: 'yellow',
            marginBottom: '12px'
          }}
        >
          Buy me a coffee!
          <EmojiFoodBeverageIcon />
        </Button>

        <Button
          href={devToUrl}
          target="_blank"
          variant="contained"
          size='large'
          style={{
            background: 'black',
            color: 'white',
            marginBottom: '12px'
          }}
        >
          Read my tech blog!
          <LogoDevIcon />
        </Button>

        <Typography variant="h6" gutterBottom component="div"
            style={{
              color: 'white',
              background: '#7289d9',
              padding: '3px 6px'
            }}
        >
          Discrod: kaede0902#6521
          <Icon icon="mdi:discord" 
            width=""
            style={{
              color: 'white',
              background: '#7289d9',
            marginBottom: '-4px'
            }}
          />
        </Typography>
 
        
      </main>
    </div>
  )
}
